services:
  db-server:
    image: mysql:8.0
    container_name: ${MY_USERNAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MY_USERNAME}
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_pass
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
    secrets:
      - db_root_pass
      - db_user_pass
    volumes:
      - db-storage:/var/lib/mysql
    networks:
      - backend-zone

  backend-php:
    image: php-fpm:latest
    container_name: ${MY_USERNAME}-php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - backend-zone

  web-proxy:
    image: nginx:latest
    container_name: ${MY_USERNAME}-web
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - backend-php
    networks:
      - frontend-zone
      - backend-zone

  db-management:
    image: phpmyadmin:latest
    container_name: ${MY_USERNAME}-pma
    restart: unless-stopped
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db-server
      PMA_PORT: 3306
      PMA_USER: ${MY_USERNAME}
      PMA_PASSWORD_FILE: /run/secrets/db_user_pass
    secrets:
      - db_user_pass
    depends_on:
      - db-server
    networks:
      - frontend-zone
      - backend-zone

networks:
  frontend-zone:
    driver: bridge
  backend-zone:
    driver: bridge

volumes:
  db-storage:

secrets:
  db_root_pass:
    file: ./secret/.db_root_pass.txt
  db_user_pass:
    file: ./secret/.db_pass_pass.txt

configs:
  nginx_default_conf:
    file: ./nginx/my-nginx.conf